spring:
  jpa:
    show-sql: false
  flyway:
    clean-disabled: true

logging:
  level:
    root: WARN
    com.thegamersstation.marketplace: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

messaging:
  ably:
    enabled: true
otp:
  isEnabled: true